### ISSUE TITLE
Better handle exceptions

### ISSUE THREAD

**Issue by pauloborba** [spgroup/miningframework#65]
(problem with github token)
Caught: main.exception.TravisHelperException: An error ocurred getting travis token
main.exception.TravisHelperException: An error ocurred getting travis token
	at main.util.TravisHelper.<init>(TravisHelper.groovy:22)
	at services.ProjectProcessorImpl.processProjects(ProjectProcessorImpl.groovy:20)
	at main.interfaces.ProjectProcessor$processProjects.call(Unknown Source)
	at main.app.MiningFramework.processProjects(MiningFramework.groovy:137)
	at main.app.MiningFramework.start(MiningFramework.groovy:79)
	at main.app.MiningFramework$start$1.call(Unknown Source)
	at main.app.MiningFramework.main(MiningFramework.groovy:63)

(maybe using ./SOOTAnalysisOutput as output)
#### MINING STARTED ####

Caught: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is '<' with an int value of 60
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
<!DOCTYPE html>
^
groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is '<' with an int value of 60
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
<!DOCTYPE html>
^
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:202)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValue(JsonParserCharArray.java:153)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeFromChars(JsonParserCharArray.java:43)
	at org.apache.groovy.json.internal.JsonParserCharArray.parse(JsonParserCharArray.java:380)
	at org.apache.groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:110)
	at main.util.HttpHelper.responseToJSON(HttpHelper.groovy:14)
	at main.util.HttpHelper$responseToJSON$2.call(Unknown Source)
	at main.util.TravisHelper.<init>(TravisHelper.groovy:24)
	at services.ProjectProcessorImpl.processProjects(ProjectProcessorImpl.groovy:20)
	at main.interfaces.ProjectProcessor$processProjects.call(Unknown Source)
	at main.app.MiningFramework.processProjects(MiningFramework.groovy:137)
	at main.app.MiningFramework.start(MiningFramework.groovy:79)
	at main.app.MiningFramework$start$1.call(Unknown Source)
	at main.app.MiningFramework.main(MiningFramework.groovy:63)

(post processing when data collection wasn't successful? no merge commit?)
Processing projects
Trying to sync travis account...
STARTING PROJECT: jsoup
Cloning repository jsoup into localProject/worker0
Cloning into 'localProject/worker0'...
remote: Enumerating objects: 15251, done.
remote: Total 15251 (delta 0), reused 0 (delta 0), pack-reused 15251
Receiving objects: 100% (15251/15251), 2.95 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (6492/6492), done.
No merge commits.
Running fetch_jars script
Traceback (most recent call last):
  File "./scripts/fetch_jars.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Running parse_to_soot script
Traceback (most recent call last):
  File "./scripts/parse_to_soot.py", line 68, in <module>
    exportCsv()
  File "./scripts/parse_to_soot.py", line 13, in exportCsv
    f = open(outputPath + "/data/results.csv", "r")
FileNotFoundError: [Errno 2] No such file or directory: './SOOTAnalysisOutput/data/results.csv'
Caught: java.io.FileNotFoundException: ./SOOTAnalysisOutput/data/soot-results.csv (No such file or directory)
java.io.FileNotFoundException: ./SOOTAnalysisOutput/data/soot-results.csv (No such file or directory)
	at services.soot.SootRunner.createOutputFile(SootRunner.groovy:64)
	at services.soot.SootRunner.processScenarios(SootRunner.groovy:27)
	at services.soot.SootRunner$processScenarios.call(Unknown Source)
	at services.OutputProcessorImpl.processOutput(OutputProcessorImpl.groovy:29)
	at main.interfaces.OutputProcessor$processOutput.call(Unknown Source)
	at main.app.MiningFramework.processOutput(MiningFramework.groovy:141)
	at main.app.MiningFramework.start(MiningFramework.groovy:87)
	at main.app.MiningFramework$start$1.call(Unknown Source)
	at main.app.MiningFramework.main(MiningFramework.groovy:63)

**Comment by pauloborba** [comment]
@rafaelmotaalves  no problema de autenticação levantado por @leusonmario, melhor logar a mensagem e passar para o proximo projeto. mas os scripts mais adiante, como os de download, nao deveriam assumir que tudo foi executado bem antes. teria que ajustar isso também
